baseURL = "https://researchbriefs.netlify.app/"
languageCode = 'en-us'
title = 'Pharmacy AI Newsletter'
theme = "PaperMod"

[params]
ShowBreadCrumbs = true

[params.auth0]
domain = "dev-hgy0ilmv64t2vwb6.us.auth0.com"
clientId = "gdc8rjiQufmjTKQIF3XNASS1xAdIeNaz"

