[build]
  # Command Netlify runs to build your site
  command = "hugo"
  # The directory Hugo outputs the site to
  publish = "public"

[build.environment]
  # Set the Hugo version (match your local version: run `hugo version`)
  HUGO_VERSION = "0.151.0" 
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -D" # include drafts on preview builds
